history_file_path = "history.log"

#Parâmetros comentados de exemplo
#
#Objetivos, mostra a porcentagem que você já conseguiu desse objetivo
#
#[objectives] 
#Carro=10000 #E.G: Tenho 5000 no total, então aparecerá '❱ Carro: $10000 (50%)'
#Celular=500

#Despesas, mostra a porcentagem que uma despesa impacta no total
#
#[expenses]
#Cartão de crédito=500 #E.G: Tenho 1000 no total, então aparecerá '❰ Cartão de crédito: $500 (50%)'

# Muda o estilo de print do programa
#
#[style]
#separator="=" #Muda o separador de linhas
#separator_size=50 #Muda o tamanho do separador de linhas
#trim_list_size=100 #Muda quantos registros serão ocultos ao ver os registro (eles só não aparecem, mas são somados e filtrados) (0 desativa)
#trim_desc_size=50 #Muda o quantos caracteres são exibidos na descrição, se for mais do que definido é cortado e adicionado "..." (desabilitado por padrão)