history_file = "history.log"

#Parametros comentados de exemplo
#
#Objetivos, mostra a porcetagem que você já conseguiu desse objetivo
#
#[objectives] 
#Carro=10000 #E.G: Tenho 5000, então aparecerá Carro: 10000 (50%)
#Celular=500

# Muda o estilo de print do programa
#
#[style]
#separator="=" #Muda o separador de linhas
#separator_size=50 #Muda o tamanho do separador de linhas
#trim_size=100 #Muda quantos registros serão ocultos ao ver os registro (eles só não aparecem, mas são somados e filtrados)
#value_padding=9 #Muda o padding entre o valor e a descrição E.G: "[13/04/2026] ↑$1007.76 {esse espaço} Recebido"